### ISSUE TITLE
Payment amount should be rounded upto 2 decimal places 

### ISSUE THREAD

**Issue by vikas-mane** [vikramsofficial/finzly#4]
![image](https://user-images.githubusercontent.com/9552554/88557428-d1d6eb80-d047-11ea-99c7-26d894f129b1.png)

**Comment by vikramsofficial** [comment]
<img width="952" alt="#4 issue" src="https://user-images.githubusercontent.com/45987795/88661592-63049b80-d0f6-11ea-8f92-9259b8f7549a.PNG">
Payment amount is now round off to 2 decimals. PFA image for  reference.
