### ISSUE TITLE
Create Loan Issues (Cosmetics)

### ISSUE THREAD

**Issue by vikas-mane** [vikramsofficial/finzly#5]
Customer - should be typeahead like control where user can type - Imagine bank having 500+ customers
The Date input box should look better, the show calendar icon, on click of that calendar should be shown.
All boxes are like text - Please arrange as appropriate
Refer attached screenshot
![image](https://user-images.githubusercontent.com/9552554/88557768-44e06200-d048-11ea-944b-7cc92cb664cb.png)

**Comment by vikramsofficial** [comment]
<img width="935" alt="#5 issue" src="https://user-images.githubusercontent.com/45987795/88661494-3781b100-d0f6-11ea-82f7-f8cdaa33cf2e.PNG">
 Type-ahead and Date icon is placed. PFA image for  reference.

**Comment by vikas-mane** [comment]
Looks decent
