### ISSUE TITLE
Display payment screen should ask for LoanID

### ISSUE THREAD

**Issue by vikas-mane** [vikramsofficial/finzly#7]
@vikramsofficial 

Display payment schedule is showing schedules for loans in system.
Display payment schedule should ask for LoanID and then show schedule for respective loan only 

Attached Screenshot for reference
![image](https://user-images.githubusercontent.com/9552554/88558330-fd0e0a80-d048-11ea-9e66-f63fcdd5a6f0.png)

**Comment by vikramsofficial** [comment]
<img width="953" alt="#7 issue" src="https://user-images.githubusercontent.com/45987795/88661055-811dcc00-d0f5-11ea-904b-26af80064d89.PNG">

Issue is Fixed to select loan id. PFA image for  reference. I have updated UI code and build for the same

**Comment by vikas-mane** [comment]
closing based on screenshot, not verified post deployment
